### ISSUE TITLE
Page refresh automatically without sending complete file

### ISSUE THREAD

**Issue by kamalbilal** [beforesemicolon/BFS-Projects#2]
node version = v14.17.1
operating system = windows
browser =  Chrome Version 91.0.4472.124 (Official Build) (64-bit)
dependencies: {
    "busboy": "^0.3.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "nodemon": "^2.0.6"
  }

When I upload a file it refreshes page automatically without sending full file.
No errors in console but in network tab there is an error status "canceled"
I added a video so you can watch what's going on
https://user-images.githubusercontent.com/48208756/125331664-20cf6c80-e2fd-11eb-9e83-4d50cb91336f.mp4

**Comment by ECorreia45** [comment]
The only thing i noticed was that you uploaded an .exe file so my question is that if the same happens with other files and file types.

**Comment by kamalbilal** [comment]
yes every time same thing happens, i tried it with .exe, .rar, .zip etc

**Comment by ECorreia45** [comment]
Will take a look

**Comment by kamalbilal** [comment]
Ok

**Comment by kamalbilal** [comment]
Hi it works
I opened backend session in different vs code window and frontend in different vs code window then it works perfectly

**Comment by ECorreia45** [comment]
Okay awesome...thanks dor getting back. I was lost in what could have been the reason.
